package com.fatpiggies.game.view;

public enum TextureId {
    LOGO,
    MENU_BACKGROUND,

    // Used in the rest of the code
    PLAY_BACKGROUND,
    BLUE_PIG,
    GREEN_PIG,
    RED_PIG,
    YELLOW_PIG,

    // Farm
    PLAY_BACKGROUND_FARM,
    BLUE_PIG_FARM,
    RED_PIG_FARM,
    GREEN_PIG_FARM,
    YELLOW_PIG_FARM,

    // Volcano
    PLAY_BACKGROUND_VOLCANO,
    BLUE_PIG_VOLCANO,
    RED_PIG_VOLCANO,
    GREEN_PIG_VOLCANO,
    YELLOW_PIG_VOLCANO,

    // Pirate
    PLAY_BACKGROUND_PIRATE,
    BLUE_PIG_PIRATE,
    RED_PIG_PIRATE,
    GREEN_PIG_PIRATE,
    YELLOW_PIG_PIRATE,

    // Space
    PLAY_BACKGROUND_SPACE,
    BLUE_PIG_SPACE,
    RED_PIG_SPACE,
    GREEN_PIG_SPACE,
    YELLOW_PIG_SPACE,

    NEXT,
    PREVIOUS,

    COIN,
    OVER_BACKGROUND,
    PODIUM,
    CROSS,
    LIFE_BLUE_PIG,
    LIFE_GREEN_PIG,
    LIFE_RED_PIG,
    LIFE_YELLOW_PIG,
    OVER_BLUE_PIG,
    OVER_GREEN_PIG,
    OVER_RED_PIG,
    OVER_YELLOW_PIG,
    CROWN,
    DONUT,
    BEER,
    LIFE,
    APPLE,
    BONUS,
    BUBBLE,
    BUMP_EFFECT

}
