package com.fatpiggies.game.view;

public enum TextureId {
    LOGO,
    MENU_BACKGROUND,
    PLAY_BACKGROUND,
    PLAY_BACKGROUND_1,
    PLAY_BACKGROUND_2,
    ARROW,
    COIN,
    OVER_BACKGROUND,
    PODIUM,
    CROSS,
    BLUE_PIG,
    GREEN_PIG,
    RED_PIG,
    YELLOW_PIG,
    LIFE_BLUE_PIG,
    LIFE_GREEN_PIG,
    LIFE_RED_PIG,
    LIFE_YELLOW_PIG,
    OVER_BLUE_PIG,
    OVER_GREEN_PIG,
    OVER_RED_PIG,
    OVER_YELLOW_PIG,
    CROWN,
    DONUT,
    BEER,
    LIFE,
    APPLE,
    BONUS,
    BUBBLE,
    BUMP_EFFECT

}
